### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by tbroyer** [ozwillo/ozwillo-java-spring-integration#13]
LGPL is an addendum to the GPL, so the GPL license must be included.

> All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.
>
> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights.

— _Source: [https://www.gnu.org/licenses/gpl-howto.html](https://www.gnu.org/licenses/gpl-howto.html)_

According to http://choosealicense.com/licenses/lgpl-3.0/ you could include both in the same file.

For oasis-php-integration, we chose to make the license explicit in the README because the use of 2 files (or putting the LGPL at the end of the LICENSE file, which then starts with the GPL) blurs the lines and there are risks that people misunderstand the license for the GPL. See pole-numerique/oasis-php-integration@cd3dfd142a582442e5d214d4249929a21444e856

**Comment by MLE-Astek** [comment]
Fixed
https://github.com/ozwillo/ozwillo-java-spring-integration/commit/c581b6a0d4414d8c5867feb01711f0e28244d711
https://github.com/ozwillo/ozwillo-java-spring-integration/commit/96449659163d3905f2512fa7d0876eb8d4effd05
